[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
    'cd smart-city-traveler-frontend && npm ci'
]

[phases.build]
cmds = [
    'cd smart-city-traveler-frontend && npm run build'
]

[start]
cmd = 'cd smart-city-traveler-frontend && npx serve -s build -l 3000'