server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: smart-city-traveler
  
  datasource:
    url: jdbc:mysql://localhost:3306/smart_city_traveler?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000 # 24 hours

# External APIs
external:
  google:
    maps:
      api-key: ${GOOGLE_MAPS_API_KEY:your-google-maps-api-key}
  zomato:
    api-key: ${ZOMATO_API_KEY:your-zomato-api-key}

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.smartcity.traveler: DEBUG
    org.springframework.security: DEBUG
